pipeline {
    agent any

    stages {
        stage('Run JMeter Test') {
            steps {
                
                dir('JMETER') {
                    bat 'if exist results rmdir /s /q results && mkdir results'
                    
                    bat 'call C:\\JMETER\\apache-jmeter-5.6.3\\bin\\jmeter.bat -n -t Task_recorder_1.jmx -l results\\result.jtl -e -o results\\report'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'JMETER/results/report/index.html, JMETER/results/result.jtl', 
                             fingerprint: true, 
                             allowEmptyArchive: true

            publishHTML(target: [
                reportDir: 'JMETER/results/report',
                reportFiles: 'index.html',
                reportName: 'JMeter Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])
        }
    }
}
