pipeline {
    agent any

    stages {
        stage('Run Lighthouse Test') {
            steps {
            
                dir('LIGHTHOUSE') {
                    bat '''
                    docker run --rm ^
                    -v %cd%:/app ^
                    -w /app ^
                    --add-host=wp:host-gateway ^
                    ghcr.io/puppeteer/puppeteer:latest ^
                    sh -c "npm install && node index2.js"
                    '''
                }
            }
        }
    }

    post {
        always {
            
            archiveArtifacts artifacts: 'LIGHTHOUSE/lighthouse-report-1.html', 
                             fingerprint: true, 
                             allowEmptyArchive: true

            publishHTML(target: [
                reportDir: 'LIGHTHOUSE', 
                reportFiles: 'lighthouse-report-1.html',
                reportName: 'Lighthouse Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])
        }
    }
}
