pipeline {
    agent any

    stages {
        stage('Run Gatling Test') {
            steps {
                dir('GATLING') {
                    
                    bat 'mvn gatling:test'
                }
            }
        }
    }

    post {
        always {
            
            archiveArtifacts artifacts: 'GATLING/target/gatling/**/*', 
                             fingerprint: true, 
                             allowEmptyArchive: true

            
            publishHTML(target: [
                reportDir: 'GATLING/target/gatling',
                reportFiles: '**/index.html',
                reportName: 'Gatling Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])
        }
    }
}
